[tool.mypy]
disallow_untyped_defs = true
disallow_incomplete_defs = true
ignore_missing_imports = true
python_version = "3.12"
strict_optional = true
warn_no_return = false
disable_error_code = ["name-defined"]

[tool.pytest.ini_options]
filterwarnings = "ignore::DeprecationWarning:starlette.*|aiofiles.*|importlib.*|flyte.*|limits:"
testpaths = "tests"

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
fixable = ["ALL"]
ignore = ["A003", "COM812", "E401", "E402", "E501", "F541", "F821", "G004", "N805", "PTH123", "S101", "TRY003", "RUF012", "RUF100", "SLF001", "TRY400"]
ignore-init-module-imports = true
select = ["A", "ASYNC", "B", "C4", "COM", "DTZ", "E", "EXE", "F", "FLY", "G", "I001", "ICN", "INP", "N", "PERF", "PT", "PTH", "RET", "RUF", "S", "SIM", "SLF", "T10", "T20", "TRY", "UP", "W"]

[tool.ruff.lint.flake8-bugbear]
extend-immutable-calls = ["fastapi.Body", "fastapi.Depends", "fastapi.Query", "fastapi.datastructures.Default"]

[tool.ruff.lint.isort]
lines-after-imports = 2

[tool.ruff.lint.mccabe]
max-complexity = 20
